package com.example.pristineseed.model.TspModel;

public class TrialSeedModel {
    
      public boolean condition;
      public String tsp_code;
      public String tsp_type;
      public String hybrid;
      public String location;
      public String zone;
      public String area;
      public String staggering_followed;
      public String staggering_recommended;
      public String type_of_soil;
      public String date_of_sowing;
      public String sowing_detail_male;
      public String sowing_detail_female;
      public String sowing_detail_other;
      public String row_ratio_female_recommended;
      public String row_ratio_female_followed;
      public String row_ratio_male_recommended;
      public String row_ratio_male_followed;
      public String seed_rate_female_recommended;
      public String seed_rate_female_followed;
      public String seed_rate_male_recommended;
      public String seed_rate_male_followed;
      public String sowing_window_from;
      public String sowing_window_to;
      public String male_parent_pollen_load;
      public String male_parent_shedding_days;
      public String male_parent_tassel_trait;
      public String female_parent_stigma_receptivity;
      public String female_parent_senstivity_to_low_tempr;
      public String female_parent_silk_receptivity;
      public String female_parent_uniformity_of_silking;
      public String diseases_and_severity_female;
      public String diseases_and_severity_male;
      public String insectpest_incidence_female;
      public String insectpest_incidence_male;
      public String maturity_from;
      public String maturity_to;
      public String potential_seed_yield_from;
      public String potential_seed_yield_to;
      public String areas_of_advantage;
      public String challenges;
      public String areas_of_concern;
      public String produciblity_of_hybrid;
      public String key_notes;
      public String created_by;
      public String created_on;
}
